#!/bin/bash
# DjangoCLI — Interactive Setup Wizard
# Run: chmod +x setup.sh && ./setup.sh

set -e

BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo ""
echo -e "${BOLD}╔══════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║         DjangoCLI Setup Wizard           ║${NC}"
echo -e "${BOLD}║   Personal AI Assistant over iMessage     ║${NC}"
echo -e "${BOLD}╚══════════════════════════════════════════╝${NC}"
echo ""

# Check prerequisites
echo -e "${BOLD}Checking prerequisites...${NC}"

if ! command -v python3 &> /dev/null; then
    echo -e "${RED}ERROR: python3 not found. Install Python 3.10+ first.${NC}"
    exit 1
fi
echo -e "  ${GREEN}✓${NC} Python3 found: $(python3 --version)"

if ! command -v swift &> /dev/null; then
    echo -e "${RED}ERROR: swift not found. Install Xcode Command Line Tools: xcode-select --install${NC}"
    exit 1
fi
echo -e "  ${GREEN}✓${NC} Swift found: $(swift --version 2>&1 | head -1)"

if [[ "$(uname)" != "Darwin" ]]; then
    echo -e "${RED}ERROR: DjangoCLI server requires macOS (for Calendar, Contacts, Reminders access).${NC}"
    echo -e "       The bot can run anywhere, but the server must be on a Mac."
    exit 1
fi
echo -e "  ${GREEN}✓${NC} macOS detected"
echo ""

# ============================================================
# Collect Configuration
# ============================================================
echo -e "${BOLD}Step 1: Your Identity${NC}"
echo ""

read -p "  Your name: " OWNER_NAME
read -p "  Your phone number (with country code, e.g. +15551234567): " PHONE_NUMBER
read -p "  Your timezone [America/New_York]: " TIMEZONE
TIMEZONE=${TIMEZONE:-America/New_York}
echo ""

echo -e "${BOLD}Step 2: API Keys${NC}"
echo ""

echo "  Get your Anthropic API key from: https://console.anthropic.com/settings/keys"
read -p "  Anthropic API key: " ANTHROPIC_KEY
echo ""

echo "  Get SendBlue keys from: https://sendblue.co/dashboard"
read -p "  SendBlue API key: " SENDBLUE_KEY
read -p "  SendBlue secret key: " SENDBLUE_SECRET
read -p "  SendBlue phone number [+13054507715]: " SENDBLUE_FROM
SENDBLUE_FROM=${SENDBLUE_FROM:-+13054507715}
echo ""

echo "  Brave Search API (optional, for web search): https://api.search.brave.com/"
read -p "  Brave Search API key [skip]: " BRAVE_KEY
echo ""

echo -e "${BOLD}Step 3: Server Configuration${NC}"
echo ""

# Generate API key
SERVER_API_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
echo -e "  Generated server API key: ${GREEN}${SERVER_API_KEY}${NC}"

read -p "  Vault path (Obsidian vault) [~/Desktop/BRAIN]: " VAULT_PATH
VAULT_PATH=${VAULT_PATH:-~/Desktop/BRAIN}

read -p "  Server bind address [0.0.0.0]: " SERVER_HOST
SERVER_HOST=${SERVER_HOST:-0.0.0.0}

read -p "  Server port [8000]: " SERVER_PORT
SERVER_PORT=${SERVER_PORT:-8000}
echo ""

echo -e "${BOLD}Step 4: Optional Integrations${NC}"
echo ""

read -p "  Gmail address (for email access, press Enter to skip): " GMAIL_EMAIL
GMAIL_APP_PASSWORD=""
if [ -n "$GMAIL_EMAIL" ]; then
    echo "  Generate an App Password at: https://myaccount.google.com/apppasswords"
    read -p "  Gmail App Password: " GMAIL_APP_PASSWORD
fi
echo ""

read -p "  Enable Whoop integration? [y/N]: " WHOOP_ENABLE
WHOOP_ENABLED=false
if [[ "$WHOOP_ENABLE" =~ ^[Yy]$ ]]; then
    WHOOP_ENABLED=true
fi

echo ""
read -p "  Your latitude (for weather) [40.7128]: " WEATHER_LAT
WEATHER_LAT=${WEATHER_LAT:-40.7128}
read -p "  Your longitude [−74.0060]: " WEATHER_LON
WEATHER_LON=${WEATHER_LON:--74.0060}
read -p "  Your city name [New York]: " WEATHER_CITY
WEATHER_CITY=${WEATHER_CITY:-New York}
echo ""

echo -e "${BOLD}Step 5: Bot Personality${NC}"
echo ""
read -p "  Bot name [Django]: " BOT_NAME
BOT_NAME=${BOT_NAME:-Django}
echo ""

# ============================================================
# Write config.yaml
# ============================================================
echo -e "${BOLD}Writing config.yaml...${NC}"

cat > config.yaml << YAML
# DjangoCLI Configuration — Generated by setup.sh on $(date +%Y-%m-%d)

owner:
  name: "${OWNER_NAME}"
  phone_number: "${PHONE_NUMBER}"
  timezone: "${TIMEZONE}"

api_keys:
  anthropic: "${ANTHROPIC_KEY}"
  sendblue_key: "${SENDBLUE_KEY}"
  sendblue_secret: "${SENDBLUE_SECRET}"
  sendblue_from: "${SENDBLUE_FROM}"
  brave_search: "${BRAVE_KEY}"

server:
  api_key: "${SERVER_API_KEY}"
  host: "${SERVER_HOST}"
  port: ${SERVER_PORT}
  vault_path: "${VAULT_PATH}"

gmail:
  email: "${GMAIL_EMAIL}"
  app_password: "${GMAIL_APP_PASSWORD}"

whoop:
  credentials_path: "~/.djangocli/whoop_credentials.json"

weather:
  latitude: ${WEATHER_LAT}
  longitude: ${WEATHER_LON}
  city: "${WEATHER_CITY}"

personality:
  name: "${BOT_NAME}"
  group_mode: "friendly"
  stranger_mode: "friendly"

schedule:
  morning_briefing:
    enabled: true
    hour: 9
    minute: 0
  evening_wrap:
    enabled: true
    hour: 22
    minute: 0

tools:
  web_search: true
  vault: true
  calendar: true
  contacts: true
  reminders: true
  messages: true
  email: $([ -n "$GMAIL_EMAIL" ] && echo "true" || echo "false")
  whoop: ${WHOOP_ENABLED}
  weather: true
  expenses: true
  habits: true
  lists: true

advanced:
  claude_model: "claude-sonnet-4-6"
  max_tokens: 1024
  conversation_history_limit: 20
  fact_extraction: true
  proactive_checks: true
  proactive_check_interval_minutes: 15
YAML

echo -e "  ${GREEN}✓${NC} config.yaml written"
echo ""

# ============================================================
# Set up Obsidian Vault
# ============================================================
EXPANDED_VAULT=$(eval echo "$VAULT_PATH")
if [ ! -d "$EXPANDED_VAULT" ]; then
    echo -e "${BOLD}Setting up Obsidian vault at ${VAULT_PATH}...${NC}"
    cp -r vault-template/ "$EXPANDED_VAULT"
    # Replace placeholder in CLAUDE.md with owner name
    sed -i '' "s/<!-- Fill in your personal context file and update this pointer -->/${OWNER_NAME}'s personal AI vault/" "$EXPANDED_VAULT/CLAUDE.md" 2>/dev/null
    echo -e "  ${GREEN}✓${NC} Vault created with starter template"
    echo "  Open in Obsidian: File > Open Vault > ${EXPANDED_VAULT}"
else
    echo -e "${BOLD}Vault already exists at ${VAULT_PATH} — skipping template copy.${NC}"
    echo "  If you want the starter template, copy manually: cp -r vault-template/* ${VAULT_PATH}/"
fi
echo ""

# ============================================================
# Compile pim-tool
# ============================================================
echo -e "${BOLD}Compiling pim-tool (Swift binary for Calendar/Contacts/Reminders)...${NC}"

cd server
if [ -f pim-tool.swift ]; then
    swiftc pim-tool.swift -o pim-tool -O 2>/dev/null
    if [ -f pim-tool ]; then
        echo -e "  ${GREEN}✓${NC} pim-tool compiled successfully"
    else
        echo -e "  ${RED}✗${NC} pim-tool compilation failed. You may need to run: swiftc pim-tool.swift -o pim-tool"
    fi
else
    echo -e "  ${RED}✗${NC} pim-tool.swift not found in server/"
fi
cd ..
echo ""

# ============================================================
# Set up Python environments
# ============================================================
echo -e "${BOLD}Setting up Python environments...${NC}"

echo "  Setting up server..."
cd server
python3 -m venv venv
source venv/bin/activate
pip install -q -r requirements.txt 2>/dev/null
deactivate
echo -e "  ${GREEN}✓${NC} Server dependencies installed"
cd ..

echo "  Setting up bot..."
cd bot
python3 -m venv venv
source venv/bin/activate
pip install -q -r requirements.txt 2>/dev/null
deactivate
echo -e "  ${GREEN}✓${NC} Bot dependencies installed"
cd ..
echo ""

# ============================================================
# Create launchd plist for server
# ============================================================
echo -e "${BOLD}Creating launchd service for auto-start...${NC}"

DJANGOCLI_DIR="$(pwd)"
PLIST_PATH="$HOME/Library/LaunchAgents/com.djangocli.server.plist"

cat > "$PLIST_PATH" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.djangocli.server</string>
    <key>ProgramArguments</key>
    <array>
        <string>${DJANGOCLI_DIR}/server/venv/bin/python3</string>
        <string>${DJANGOCLI_DIR}/server/server.py</string>
    </array>
    <key>WorkingDirectory</key>
    <string>${DJANGOCLI_DIR}/server</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>DJANGOCLI_CONFIG</key>
        <string>${DJANGOCLI_DIR}/config.yaml</string>
    </dict>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>/tmp/djangocli-server.log</string>
    <key>StandardErrorPath</key>
    <string>/tmp/djangocli-server.err</string>
</dict>
</plist>
PLIST

echo -e "  ${GREEN}✓${NC} Created ${PLIST_PATH}"
echo ""

# ============================================================
# Create DjangoCLI config directory
# ============================================================
mkdir -p ~/.djangocli
echo -e "  ${GREEN}✓${NC} Created ~/.djangocli/"
echo ""

# ============================================================
# Grant TCC Permissions
# ============================================================
echo -e "${BOLD}${YELLOW}IMPORTANT: TCC Permissions Required${NC}"
echo ""
echo "  macOS requires explicit permission for Calendar, Contacts, and Reminders access."
echo "  Run these commands in Terminal to trigger the permission dialogs:"
echo ""
echo -e "    ${GREEN}./server/pim-tool calendar today${NC}"
echo -e "    ${GREEN}./server/pim-tool reminders list${NC}"
echo -e "    ${GREEN}./server/pim-tool contacts search \"test\"${NC}"
echo ""
echo "  Click 'Allow' on each popup that appears."
echo ""

# ============================================================
# Summary
# ============================================================
echo -e "${BOLD}╔══════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║           Setup Complete!                ║${NC}"
echo -e "${BOLD}╚══════════════════════════════════════════╝${NC}"
echo ""
echo -e "${BOLD}What's next:${NC}"
echo ""
echo "  1. Grant TCC permissions (commands above)"
echo ""
echo "  2. Start the Mac Mini server:"
echo -e "     ${GREEN}launchctl load ~/Library/LaunchAgents/com.djangocli.server.plist${NC}"
echo "     Or manually:"
echo -e "     ${GREEN}cd server && source venv/bin/activate && python3 server.py${NC}"
echo ""
echo "  3. Test the server:"
echo -e "     ${GREEN}curl -H 'x-api-key: ${SERVER_API_KEY}' http://localhost:${SERVER_PORT}/health${NC}"
echo ""
echo "  4. Deploy the bot to Render (or run locally):"
echo ""
echo "     ${BOLD}Render:${NC}"
echo "     - Create a new Web Service from the bot/ directory"
echo "     - Set environment variables:"
echo -e "       ${GREEN}DJANGOCLI_CONFIG${NC} = (not needed if config.yaml is in repo root)"
echo -e "       ${GREEN}MAC_MINI_URL${NC} = http://YOUR_TAILSCALE_IP:${SERVER_PORT}"
echo -e "       ${GREEN}MAC_MINI_API_KEY${NC} = ${SERVER_API_KEY}"
echo "       ...plus all API keys from config.yaml as env vars"
echo "     - Set webhook URL in SendBlue: https://YOUR-APP.onrender.com/webhook"
echo ""
echo "     ${BOLD}Local:${NC}"
echo -e "     ${GREEN}cd bot && source venv/bin/activate && python3 app.py${NC}"
echo ""
echo "  5. Set up Tailscale for remote access:"
echo "     - Install Tailscale on this Mac and your deployment server"
echo "     - Update server bind address to your Tailscale IP"
echo "     - Update MAC_MINI_URL in bot config to Tailscale address"
echo ""
echo -e "  ${BOLD}Config file:${NC} $(pwd)/config.yaml"
echo -e "  ${BOLD}Server logs:${NC} /tmp/djangocli-server.log"
echo -e "  ${BOLD}Bot name:${NC} ${BOT_NAME}"
echo ""
echo -e "  ${GREEN}Text your bot's SendBlue number to test it!${NC}"
echo ""
